version: "3.7"

services:
  islb:
    image: pionwebrtc/ion:latest-islb
    build:
      dockerfile: ./docker/islb.Dockerfile
      context: .
    volumes:
      - "./configs/docker/islb.toml:/configs/islb.toml"
    depends_on:
      - nats
      - redis
    networks:
      - ionnet

  sfu:
    image: pionwebrtc/ion:latest-sfu
    build:
      dockerfile: ./docker/sfu.Dockerfile
      context: .
    volumes:
      - "./configs/docker/sfu.toml:/configs/sfu.toml"
    ports:
      - "15000-15200:15000-15200/udp"
      - 3478:3478
    depends_on:
      - nats
      - islb
    networks:
      - ionnet

  avp:
    image: pionwebrtc/ion:latest-avp
    build:
      dockerfile: ./docker/avp.Dockerfile
      context: .
    volumes:
      - "./configs/docker/avp.toml:/configs/avp.toml"
      - "./out:/out/"
    depends_on:
      - nats
      - islb
    networks:
      - ionnet

  biz:
    image: pionwebrtc/ion:latest-biz
    build:
      dockerfile: ./docker/biz.Dockerfile
      context: .
    volumes:
      - "./configs/docker/biz.toml:/configs/biz.toml"
    ports:
      - 5551:5551
    depends_on:
      - nats
      - islb
    networks:
      - ionnet

  nats:
    image: nats
    ports:
      - 4222:4222
    networks:
      - ionnet

  redis:
    image: redis:6.2.3
    ports:
      - 6379:6379
    networks:
      - ionnet

networks:
  ionnet:
    external: true
    name: ionnet
    driver: bridge
